### ISSUE TITLE
Todo for Interconnect ASAP

### ISSUE THREAD

**Issue by ckelner** [matthiaskubik/tf-templates#2]
- [x] Concatenate all the terraform and provisioner files into one
- [x] Update the README for the new resources/architecture
  - [x] Add arch diagram
  - [x] Add terraform graph
- [x] Comment all the resource blocks and properties
- [x] Put demo steps into README
- [x] Put Terraform docs online somewhere

**Comment by ckelner** [comment]
https://control.bluemix.net/devices

**Comment by ckelner** [comment]
https://control.bluemix.net/network/loadbalancing/local

**Comment by ckelner** [comment]
https://control.bluemix.net/devices/sshkeys

**Comment by ckelner** [comment]
http://192.168.99.100:4567/docs/providers/ibmcloud/index.html

**Comment by ckelner** [comment]
http://ibmcloudterraformdocs.chriskelner.com/docs/providers/ibmcloud/index.html
